INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BZ881BZ', 'Mercedes-Benz Sprinter 2500 Cargo', 56, 60);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YA882YA', 'Ford Transit 350 Van', 35, 455);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WZ018WZ', 'Kia Cadenza', 51, 48);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VK146VK', 'Jeep Compass', 44, 279);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QA137QA', 'Audi S3', 61, 365);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KO739KO', 'MINI Hardtop 4 Door', 1, 466);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NG949NG', 'Honda Cr-Z', 63, 186);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IG567IG', 'Ford F250 Super Duty Super Cab', 61, 267);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NK410NK', 'Lamborghini Aventador', 38, 306);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SS378SS', 'Nissan Nv3500 Hd Passenger', 4, 357);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IV631IV', 'Ford Transit 150 Van', 31, 18);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DO025DO', 'Lexus Rx', 44, 107);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OQ251OQ', 'Ferrari F12Berlinetta', 93, 498);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NX067NX', 'Mercedes-Benz Glk-Class', 48, 261);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UN700UN', 'Audi S7', 64, 132);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NR685NR', 'Chevrolet Captiva Sport', 70, 184);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JB951JB', 'Land Rover Lr2', 54, 296);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RI037RI', 'BMW 3 Series', 49, 123);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XC406XC', 'Rolls-Royce Wraith', 27, 379);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GQ878GQ', 'Mercedes-Benz Gl-Class', 12, 486);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RS045RS', 'Chevrolet Camaro', 89, 250);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UH211UH', 'Hyundai Azera', 73, 232);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BM744BM', 'Toyota 4Runner', 7, 311);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MH437MH', 'Toyota Tacoma Double Cab', 98, 68);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QE237QE', 'GMC Savana 3500 Passenger', 56, 175);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OC858OC', 'Mercedes-Benz Sl-Class', 47, 494);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NG689NG', 'Ferrari Ff', 56, 36);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KB580KB', 'Chevrolet Captiva Sport', 93, 497);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UD457UD', 'Lexus Nx', 91, 137);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RS301RS', 'Ford F350 Super Duty Super Cab', 56, 110);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EC531EC', 'Mercedes-Benz Cls-Class', 93, 237);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RC089RC', 'MAZDA Cx-5', 52, 151);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AU732AU', 'Jeep Wrangler', 37, 477);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VJ208VJ', 'Nissan Gt-R', 60, 476);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WP406WP', 'Ford Expedition El', 90, 353);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KG046KG', 'Volkswagen Golf Gti', 15, 256);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GM971GM', 'Ford Mustang', 97, 208);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FX858FX', 'Toyota Sequoia', 9, 363);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VQ888VQ', 'Ram C/V Tradesman', 61, 21);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AB791AB', 'Ford F150 Regular Cab', 41, 188);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RW547RW', 'Porsche Cayman', 69, 207);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IX961IX', 'Ford Escape', 41, 52);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DK376DK', 'Porsche Boxster', 25, 33);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FO214FO', 'Nissan Rogue Select', 17, 145);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KY512KY', 'MAZDA Mx-5 Miata', 80, 149);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DW648DW', 'Chevrolet Silverado 1500 Regular Cab', 77, 80);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EM378EM', 'GMC Sierra 2500 Hd Double Cab', 32, 376);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WH611WH', 'Audi A7', 57, 355);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BW955BW', 'Volvo Xc60', 5, 381);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EM220EM', 'Bentley Flying Spur', 60, 370);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZN274ZN', 'Chevrolet Spark Ev', 39, 348);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PW439PW', 'Volkswagen Jetta', 87, 37);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XS761XS', 'Lexus Gx', 28, 289);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IJ464IJ', 'Land Rover Lr4', 7, 410);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RA944RA', 'GMC Acadia', 85, 176);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IH212IH', 'Nissan Frontier King Cab', 36, 296);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OV978OV', 'Dodge Durango', 68, 113);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HU647HU', 'Chrysler 300', 63, 422);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QA296QA', 'Kia Soul Ev', 26, 332);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XD434XD', 'GMC Savana 3500 Passenger', 94, 127);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RU910RU', 'Honda Odyssey', 88, 130);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BU112BU', 'Scion Xb', 89, 19);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('US986US', 'Ford Transit 150 Wagon', 58, 453);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KY105KY', 'Cadillac Srx', 13, 7);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XA404XA', 'MINI Roadster', 56, 155);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PH025PH', 'Buick Encore', 5, 56);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DL254DL', 'GMC Yukon Xl', 88, 4);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VJ716VJ', 'Chevrolet Express 2500 Cargo', 42, 162);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MR212MR', 'BMW M4', 76, 456);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UI705UI', 'Aston Martin Db9', 11, 313);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QX382QX', 'GMC Savana 3500 Cargo', 62, 295);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LS893LS', 'Chevrolet Express 3500 Cargo', 54, 210);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IV785IV', 'Bentley Continental', 23, 250);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BD804BD', 'Ferrari 458 Spider', 27, 52);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NR587NR', 'Audi A6', 76, 268);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IY695IY', 'GMC Sierra 1500 Regular Cab', 86, 7);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SM861SM', 'GMC Savana 3500 Cargo', 11, 20);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LE158LE', 'Subaru Xv Crosstrek', 45, 180);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UQ681UQ', 'Lexus Es', 23, 192);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FF791FF', 'Toyota Prius', 59, 448);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YH382YH', 'Toyota 4Runner', 48, 55);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LM486LM', 'Honda Fit', 18, 292);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EU413EU', 'Jaguar Xf', 29, 393);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZS616ZS', 'Nissan Xterra', 89, 329);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AY269AY', 'Audi S5', 51, 258);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NR940NR', 'Mercedes-Benz C-Class', 43, 156);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CT991CT', 'Ford Fiesta', 42, 465);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JH361JH', 'Chrysler 300', 11, 16);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YC008YC', 'Chrysler 200', 30, 224);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NO217NO', 'Volvo S80', 16, 368);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LP511LP', 'Buick Regal', 40, 82);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IQ057IQ', 'Lexus Gx', 41, 302);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EC195EC', 'Volkswagen Passat', 35, 404);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CH909CH', 'BMW M5', 16, 359);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('US793US', 'Mercedes-Benz E-Class', 39, 395);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SO666SO', 'Lincoln Mkx', 24, 111);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XZ387XZ', 'Chevrolet Spark Ev', 11, 447);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FE322FE', 'BMW 7 Series', 61, 455);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VU691VU', 'Mercedes-Benz Sls-Class', 90, 404);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PO992PO', 'Toyota Prius', 22, 328);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QS518QS', 'MINI Coupe', 53, 50);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QR886QR', 'Scion Fr-S', 47, 266);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GN366GN', 'Volkswagen Tiguan', 25, 190);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EB819EB', 'Tesla Model S', 36, 438);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DT888DT', 'Subaru Forester', 62, 101);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IM589IM', 'Buick Lacrosse', 6, 138);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NV910NV', 'Chevrolet Colorado Extended Cab', 91, 433);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UR997UR', 'Aston Martin Db9', 88, 201);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RB813RB', 'Ferrari F12Berlinetta', 59, 104);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KN806KN', 'Hyundai Genesis Coupe', 93, 135);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PP370PP', 'Nissan Frontier King Cab', 67, 258);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FB682FB', 'Honda Cr-Z', 93, 317);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EG119EG', 'GMC Yukon', 12, 2);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MA494MA', 'Lexus Nx', 31, 444);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IX362IX', 'Volkswagen Golf Gti', 58, 215);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AY247AY', 'Volkswagen Tiguan', 56, 13);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TV662TV', 'Porsche Panamera', 96, 231);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GA200GA', 'Bentley Mulsanne', 7, 274);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DT675DT', 'Buick Lacrosse', 24, 491);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QH939QH', 'BMW 6 Series', 89, 306);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NV553NV', 'Volvo S60', 33, 6);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WN616WN', 'Volvo Xc70', 57, 460);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TB415TB', 'Volkswagen Passat', 53, 10);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JY500JY', 'Ford Transit 250 Van', 52, 130);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VS733VS', 'Mercedes-Benz Sl-Class', 10, 206);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FP480FP', 'Nissan Nv2500 Hd Cargo', 4, 417);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GF583GF', 'Ford F450 Super Duty Crew Cab', 84, 358);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GS837GS', 'Lamborghini Huracan', 71, 2);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SF730SF', 'INFINITI Q50', 9, 99);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QD428QD', 'make Model', 81, 337);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JI287JI', 'Kia Optima', 40, 308);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QH035QH', 'BMW M5', 81, 16);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XK513XK', 'Chevrolet Colorado Extended Cab', 75, 298);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WF746WF', 'Toyota Tacoma Double Cab', 98, 196);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BZ109BZ', 'Subaru Wrx', 74, 144);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OO939OO', 'Honda Odyssey', 8, 111);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JF955JF', 'Toyota Prius Plug-In Hybrid', 50, 428);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MN206MN', 'Freightliner Sprinter 2500 Passenger', 59, 80);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RI690RI', 'Audi Rs 5', 25, 482);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ND891ND', 'Scion Iq', 23, 69);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JF663JF', 'Toyota Highlander', 31, 17);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XA749XA', 'Ram Promaster Window Van', 95, 141);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YP955YP', 'Subaru Wrx', 100, 223);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SM134SM', 'Kia Sedona', 81, 318);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VR857VR', 'GMC Savana 2500 Cargo', 64, 326);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LM263LM', 'BMW X5', 96, 94);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FR377FR', 'Volkswagen Jetta', 89, 357);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GU168GU', 'Aston Martin Db9', 74, 444);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SA349SA', 'Kia Soul Ev', 89, 36);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WC532WC', 'MINI Hardtop 4 Door', 84, 454);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GI228GI', 'Mercedes-Benz Sl-Class', 38, 461);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FE463FE', 'Chevrolet Express 2500 Passenger', 94, 317);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WA675WA', 'Chevrolet Colorado Crew Cab', 5, 135);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NV862NV', 'INFINITI Q70', 77, 10);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KA185KA', 'Volkswagen Jetta', 7, 93);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VZ623VZ', 'Mercedes-Benz Sls-Class', 82, 355);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WQ508WQ', 'MAZDA Cx-9', 81, 247);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LB593LB', 'Bentley Continental', 90, 419);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BH727BH', 'Audi Rs 5', 82, 437);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JM229JM', 'Volkswagen Beetle', 42, 255);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BN259BN', 'Honda Fit', 15, 155);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UL470UL', 'Porsche Cayman', 39, 448);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JI737JI', 'Subaru Forester', 41, 23);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XL539XL', 'BMW X6', 32, 380);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IJ509IJ', 'Hyundai Elantra Gt', 14, 174);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HP441HP', 'Hyundai Elantra', 58, 436);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XD840XD', 'Honda Fit', 90, 333);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PL846PL', 'Chevrolet Silverado 2500 Hd Regular Cab', 73, 399);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DA515DA', 'Mercedes-Benz Cla-Class', 25, 418);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LR402LR', 'BMW M3', 10, 115);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WN904WN', 'Subaru Legacy', 6, 370);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GL624GL', 'Toyota Camry', 41, 244);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SE736SE', 'Chevrolet Impala Limited', 7, 498);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FH590FH', 'McLaren 650S', 77, 109);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JH200JH', 'Nissan Rogue', 38, 430);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UF284UF', 'Chevrolet Express 2500 Passenger', 3, 380);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FT176FT', 'Land Rover Range Rover Evoque', 42, 472);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ES367ES', 'MAZDA Mazda6', 65, 373);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MP152MP', 'MINI Hardtop 2 Door', 62, 276);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RP684RP', 'Ferrari Ff', 87, 378);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VO101VO', 'BMW 3 Series', 20, 473);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WL911WL', 'Mercedes-Benz Sls-Class', 25, 364);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TB254TB', 'Chevrolet Traverse', 6, 483);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EG114EG', 'Jeep Wrangler', 34, 381);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZD051ZD', 'Honda Civic', 40, 349);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BG577BG', 'Alfa Romeo 4C', 59, 32);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TY329TY', 'Volkswagen Jetta', 38, 479);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UA774UA', 'Cadillac Xts', 84, 276);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TP267TP', 'Jeep Cherokee', 57, 92);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EQ067EQ', 'Volkswagen Cc', 50, 473);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IQ089IQ', 'BMW 7 Series', 76, 364);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WJ998WJ', 'Nissan Gt-R', 90, 105);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LY342LY', 'Mercedes-Benz S-Class', 81, 3);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EA275EA', 'Lincoln Mkc', 79, 206);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MO260MO', 'Nissan Versa', 99, 259);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CR279CR', 'BMW 3 Series', 18, 269);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TI023TI', 'Dodge Challenger', 57, 41);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OW854OW', 'Buick Enclave', 21, 25);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KU232KU', 'Chevrolet Corvette', 6, 158);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QJ674QJ', 'Ford F350 Super Duty Regular Cab', 18, 439);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QC394QC', 'Ford Expedition', 73, 176);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JG861JG', 'Hyundai Accent', 99, 25);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XC643XC', 'Volvo S60', 44, 226);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KJ964KJ', 'Mitsubishi Lancer Evolution', 16, 333);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZK178ZK', 'BMW X6', 31, 422);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BF394BF', 'INFINITI Q70', 69, 430);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YA199YA', 'Volkswagen Jetta', 58, 79);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZV929ZV', 'Kia Sportage', 100, 44);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QL405QL', 'Ram 3500 Regular Cab', 63, 175);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XN697XN', 'Hyundai Veloster', 59, 119);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MX870MX', 'Jaguar Xj', 33, 262);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VT365VT', 'Chevrolet Ss', 12, 441);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EL012EL', 'Subaru Xv Crosstrek', 66, 332);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QE724QE', 'Volkswagen Golf R', 32, 217);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DV172DV', 'Lincoln Navigator', 26, 183);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HV403HV', 'MINI Hardtop 4 Door', 29, 160);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BL407BL', 'Land Rover Range Rover', 72, 376);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GW517GW', 'Nissan Nv2500 Hd Cargo', 28, 393);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HM758HM', 'Toyota 4Runner', 17, 226);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PZ452PZ', 'Chevrolet Express 3500 Passenger', 78, 257);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BZ392BZ', 'MAZDA Cx-5', 5, 314);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QS131QS', 'INFINITI Qx60', 1, 89);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OE409OE', 'Chrysler Town & Country', 34, 300);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FE139FE', 'Porsche Cayman', 39, 232);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MJ360MJ', 'Lamborghini Aventador', 5, 242);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FT523FT', 'Mercedes-Benz Sprinter 2500 Crew', 46, 402);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HU469HU', 'MINI Roadster', 24, 343);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ML225ML', 'Lincoln Mkt', 67, 275);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZW539ZW', 'Jeep Compass', 89, 476);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MX433MX', 'Scion Fr-S', 85, 417);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BU999BU', 'Ford C-Max Energi', 17, 14);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XD257XD', 'Ram 3500 Mega Cab', 45, 366);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PQ110PQ', 'BMW X5', 4, 392);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CS596CS', 'Cadillac Escalade Esv', 42, 75);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WD372WD', 'Ferrari 458 Italia', 75, 125);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VH610VH', 'Volkswagen Golf Sportwagen', 31, 169);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JL759JL', 'Ford Transit 150 Van', 53, 493);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JZ009JZ', 'INFINITI Qx60', 46, 294);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TM687TM', 'MINI Convertible', 48, 373);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GY153GY', 'Hyundai Santa Fe Sport', 70, 242);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OL219OL', 'Lamborghini Aventador', 51, 140);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QQ590QQ', 'Porsche 911', 98, 384);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FW808FW', 'Hyundai Genesis Coupe', 68, 156);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KX407KX', 'Toyota Avalon', 52, 463);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NB505NB', 'Honda Civic', 40, 354);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UJ874UJ', 'Nissan Gt-R', 89, 203);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AP050AP', 'GMC Yukon', 3, 310);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IQ607IQ', 'Jeep Wrangler', 49, 99);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UH475UH', 'Cadillac Srx', 26, 83);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KH081KH', 'Hyundai Genesis', 22, 374);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OP114OP', 'Honda Cr-Z', 87, 281);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PM491PM', 'Ford Transit 250 Van', 41, 326);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BT955BT', 'Jaguar Xk', 24, 11);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DK891DK', 'Ram Promaster City', 12, 425);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FT801FT', 'Nissan Gt-R', 81, 88);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZU407ZU', 'Ford Mustang', 87, 279);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NT658NT', 'BMW I8', 93, 72);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RX652RX', 'Honda Cr-V', 69, 115);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QY898QY', 'Acura Mdx', 89, 132);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TQ379TQ', 'Nissan Leaf', 82, 233);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TT420TT', 'Ford Escape', 36, 495);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AA488AA', 'Mercedes-Benz Cls-Class', 9, 227);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SU140SU', 'Kia Rio', 33, 223);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AU880AU', 'Honda Accord Hybrid', 96, 166);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RE062RE', 'GMC Terrain', 70, 225);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FX636FX', 'BMW X1', 34, 427);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CX190CX', 'Cadillac Cts', 82, 85);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LA277LA', 'INFINITI Qx50', 18, 454);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SS298SS', 'Kia Forte5', 7, 286);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SP661SP', 'smart Fortwo Electric Drive', 91, 485);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AL592AL', 'Ram 1500 Quad Cab', 96, 487);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EB336EB', 'GMC Sierra 1500 Crew Cab', 34, 208);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JZ798JZ', 'Ford Explorer', 6, 248);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PW098PW', 'Rolls-Royce Ghost', 47, 334);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EO935EO', 'Volkswagen Golf Sportwagen', 7, 67);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XV726XV', 'INFINITI Q60', 2, 377);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OT976OT', 'Toyota Corolla', 25, 29);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WE852WE', 'GMC Savana 3500 Passenger', 14, 64);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MO566MO', 'FIAT 500C', 51, 38);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PC232PC', 'Chevrolet Silverado 3500 Hd Crew Cab', 89, 347);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YL794YL', 'BMW X4', 99, 210);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WO187WO', 'Ford Explorer', 79, 166);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GT514GT', 'FIAT 500E', 36, 154);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LI765LI', 'Dodge Durango', 71, 272);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QF265QF', 'Toyota Prius', 5, 452);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZW986ZW', 'Acura Rlx', 35, 85);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YO087YO', 'Mercedes-Benz Gla-Class', 13, 186);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DK952DK', 'MAZDA Cx-5', 71, 482);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UH632UH', 'Mercedes-Benz Slk-Class', 85, 96);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CM585CM', 'Ford Expedition', 67, 500);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HG992HG', 'Nissan Juke', 16, 112);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XD297XD', 'Honda Fit', 89, 260);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UH082UH', 'Toyota Corolla', 52, 397);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BS011BS', 'Porsche Boxster', 94, 74);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XI480XI', 'Cadillac Escalade Esv', 59, 164);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BF251BF', 'Lexus Rx', 53, 292);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DU260DU', 'Ram 1500 Regular Cab', 16, 328);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JR487JR', 'Buick Lacrosse', 6, 427);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FB512FB', 'Chevrolet Silverado 3500 Hd Crew Cab', 82, 14);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RW200RW', 'GMC Sierra 3500 Hd Crew Cab', 55, 6);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JN963JN', 'Mercedes-Benz Sprinter 2500 Cargo', 26, 230);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XY246XY', 'McLaren 650S', 90, 255);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GM158GM', 'Volkswagen Golf Sportwagen', 55, 167);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MF688MF', 'Subaru Wrx', 77, 397);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YK147YK', 'Kia Sedona', 7, 441);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PQ035PQ', 'Ford Mustang', 11, 472);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FB004FB', 'Bentley Mulsanne', 36, 388);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EW349EW', 'Lexus Rx', 31, 57);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FS471FS', 'MINI Hardtop 2 Door', 54, 395);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CO523CO', 'Hyundai Equus', 85, 121);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TK028TK', 'Chevrolet Silverado 2500 Hd Double Cab', 90, 351);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PL824PL', 'GMC Sierra 2500 Hd Crew Cab', 62, 181);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KS833KS', 'BMW Z4', 64, 68);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RR980RR', 'Ford Explorer', 63, 412);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VT649VT', 'Mitsubishi Lancer Evolution', 42, 426);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TP639TP', 'Porsche Cayenne', 35, 66);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SD824SD', 'Buick Regal', 87, 165);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZI323ZI', 'make Model', 92, 346);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GB795GB', 'Ram 3500 Regular Cab', 2, 194);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VO642VO', 'Chevrolet Silverado 1500 Crew Cab', 90, 280);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JY104JY', 'Lincoln Mkc', 82, 228);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NQ542NQ', 'Ram 2500 Regular Cab', 84, 241);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JV536JV', 'Hyundai Sonata', 38, 287);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YL968YL', 'Chevrolet Sonic', 54, 72);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FM443FM', 'Audi A8', 81, 81);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VN890VN', 'Hyundai Genesis', 93, 58);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JU494JU', 'Rolls-Royce Phantom', 20, 220);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZU473ZU', 'Kia Optima Hybrid', 56, 183);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CQ673CQ', 'FIAT 500C', 32, 39);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GG768GG', 'MINI Paceman', 63, 241);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DU890DU', 'Ford Edge', 30, 408);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XX769XX', 'smart Fortwo Electric Drive', 41, 213);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BV664BV', 'Chrysler 200', 96, 248);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RN067RN', 'Nissan 370Z', 42, 120);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NV939NV', 'Chevrolet Corvette', 36, 434);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YR366YR', 'BMW M3', 19, 61);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SE382SE', 'Chevrolet Colorado Crew Cab', 58, 195);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JK074JK', 'Volkswagen Golf Gti', 100, 322);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PB962PB', 'Ram 2500 Crew Cab', 28, 428);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UL102UL', 'Chevrolet Corvette', 45, 128);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EY862EY', 'Cadillac Srx', 12, 346);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DR888DR', 'Kia Forte5', 32, 134);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EW754EW', 'MINI Paceman', 15, 136);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UN960UN', 'INFINITI Qx60', 81, 436);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NW893NW', 'Audi Allroad', 52, 284);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HT180HT', 'Chrysler 200', 29, 408);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WG222WG', 'Hyundai Tucson Fuel Cell', 8, 211);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LR972LR', 'Ram Promaster Cargo Van', 3, 53);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HI163HI', 'Nissan Nv3500 Hd Passenger', 54, 200);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GT215GT', 'Chevrolet Express 3500 Passenger', 50, 351);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TD425TD', 'Chevrolet Silverado 1500 Regular Cab', 87, 60);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CX967CX', 'INFINITI Qx70', 54, 62);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VP224VP', 'Nissan Juke', 87, 285);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HN035HN', 'MAZDA Cx-9', 76, 330);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VA732VA', 'Volvo Xc70', 15, 253);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KW046KW', 'Toyota Rav4', 35, 321);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IQ664IQ', 'BMW I3', 96, 459);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HD654HD', 'Cadillac Escalade Esv', 37, 442);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PJ970PJ', 'Volkswagen E-Golf', 97, 154);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LF984LF', 'Mercedes-Benz Cls-Class', 95, 429);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RA835RA', 'Toyota Camry', 9, 347);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JA670JA', 'Audi Rs 7', 91, 69);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YT506YT', 'Ferrari Ff', 69, 273);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MI820MI', 'Lincoln Mkx', 60, 131);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FV274FV', 'Mercedes-Benz Sprinter 2500 Passenger', 10, 235);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KD314KD', 'MAZDA Mazda6', 28, 218);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LP850LP', 'Audi S7', 54, 55);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GK169GK', 'Toyota Avalon', 5, 106);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MU819MU', 'Volkswagen Golf R', 93, 228);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZF657ZF', 'Chevrolet Impala Limited', 91, 400);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HW655HW', 'Hyundai Azera', 13, 431);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EG804EG', 'Lexus Gs', 97, 354);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RN873RN', 'Nissan Nv200', 77, 415);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GI327GI', 'Ford Transit 150 Wagon', 42, 446);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BX732BX', 'Alfa Romeo 4C', 3, 463);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GR043GR', 'Nissan Pathfinder', 89, 310);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IZ688IZ', 'Lincoln Mkz', 33, 51);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MJ526MJ', 'Scion Tc', 90, 8);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EC363EC', 'Ford Expedition', 60, 446);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ET265ET', 'Bentley Flying Spur', 61, 341);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EI011EI', 'make Model', 86, 369);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XI654XI', 'Volvo V60', 5, 40);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IZ816IZ', 'Jaguar Xf', 15, 83);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XS876XS', 'Bentley Mulsanne', 44, 465);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MJ118MJ', 'Chevrolet Trax', 73, 152);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IR544IR', 'Kia Forte', 87, 98);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MS596MS', 'Land Rover Discovery Sport', 71, 331);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QR347QR', 'Ford C-Max Hybrid', 25, 400);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OC784OC', 'MAZDA Mx-5 Miata', 14, 480);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JZ579JZ', 'BMW M6', 35, 116);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QI131QI', 'GMC Sierra 2500 Hd Crew Cab', 91, 49);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KF232KF', 'Lamborghini Aventador', 69, 136);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JT818JT', 'Toyota Land Cruiser', 78, 359);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MU073MU', 'Buick Encore', 44, 429);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OM665OM', 'GMC Acadia', 63, 32);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZG087ZG', 'Kia Optima Hybrid', 100, 453);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TS246TS', 'Dodge Challenger', 62, 353);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AB466AB', 'Volkswagen Eos', 43, 369);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CL133CL', 'Kia Rio', 14, 464);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XF332XF', 'Lamborghini Huracan', 32, 290);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LB230LB', 'Audi S8', 64, 164);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AU056AU', 'Honda Crosstour', 56, 271);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SG217SG', 'Mitsubishi Outlander Sport', 6, 262);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KQ658KQ', 'Volkswagen Eos', 34, 365);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VD605VD', 'Subaru Wrx', 48, 323);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RB633RB', 'Land Rover Lr4', 97, 360);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JO356JO', 'Dodge Viper', 74, 216);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RP320RP', 'Land Rover Lr4', 27, 469);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MD835MD', 'Kia Sportage', 7, 479);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HQ884HQ', 'Jeep Patriot', 14, 396);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CG653CG', 'BMW X5', 53, 299);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VY142VY', 'Chevrolet Silverado 1500 Crew Cab', 2, 267);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SM912SM', 'Nissan Armada', 38, 261);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZN638ZN', 'Mercedes-Benz Cls-Class', 93, 387);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KH826KH', 'Acura Rlx', 76, 149);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KQ099KQ', 'Audi A3', 97, 91);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TX425TX', 'Audi R8', 42, 202);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PW623PW', 'Mercedes-Benz S-Class', 59, 191);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TQ843TQ', 'GMC Sierra 1500 Regular Cab', 59, 20);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GE827GE', 'Ram Promaster Window Van', 63, 294);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YI753YI', 'Ford F350 Super Duty Super Cab', 62, 214);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WR398WR', 'GMC Acadia', 77, 157);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DX044DX', 'Land Rover Range Rover Sport', 50, 142);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ML312ML', 'Jaguar F-Type', 94, 234);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZY263ZY', 'Nissan Rogue', 100, 464);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MR457MR', 'Hyundai Veloster', 7, 112);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XJ373XJ', 'Hyundai Veloster', 16, 66);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TS265TS', 'Lamborghini Huracan', 40, 291);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IV885IV', 'Ford Fiesta', 3, 245);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NZ440NZ', 'Ram 1500 Quad Cab', 9, 65);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FO564FO', 'Subaru Xv Crosstrek', 54, 285);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AK510AK', 'Lamborghini Huracan', 98, 336);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AB324AB', 'Audi A8', 49, 239);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KR826KR', 'Ford Taurus', 19, 152);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DR211DR', 'Alfa Romeo 4C', 15, 197);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SJ375SJ', 'Ram 1500 Quad Cab', 83, 358);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WU225WU', 'Subaru Impreza', 14, 469);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XM335XM', 'Chevrolet Corvette', 99, 184);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TA167TA', 'MINI Countryman', 55, 125);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TT739TT', 'Kia Forte', 66, 177);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WE573WE', 'MAZDA Cx-9', 98, 468);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NU188NU', 'Nissan Sentra', 81, 244);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AK982AK', 'GMC Savana 3500 Cargo', 15, 297);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VE086VE', 'BMW 5 Series', 24, 147);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XS963XS', 'Chevrolet Spark Ev', 36, 193);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IB087IB', 'Subaru Legacy', 56, 431);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KL669KL', 'Ford Fusion', 87, 316);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TB348TB', 'Cadillac Srx', 56, 197);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LY442LY', 'Chevrolet Silverado 1500 Regular Cab', 92, 199);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CI802CI', 'Ford Expedition', 65, 100);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HO750HO', 'INFINITI Q40', 45, 126);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XY483XY', 'Ford Transit 250 Van', 41, 81);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IU823IU', 'Scion Tc', 56, 329);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JJ386JJ', 'Nissan Sentra', 47, 192);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ID239ID', 'Scion Iq', 53, 75);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LM130LM', 'Nissan Leaf', 67, 321);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LE823LE', 'Volvo Xc70', 80, 131);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AV245AV', 'Ram C/V Tradesman', 18, 350);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KO242KO', 'MINI Paceman', 60, 349);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CO580CO', 'Nissan Altima', 42, 142);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YT902YT', 'Mercedes-Benz Gla-Class', 21, 63);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NV213NV', 'MAZDA Mx-5 Miata', 4, 11);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JV873JV', 'Toyota Tacoma Access Cab', 51, 35);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JX871JX', 'Chevrolet Silverado 2500 Hd Double Cab', 61, 198);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YO426YO', 'MINI Coupe', 33, 151);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FD996FD', 'Nissan Leaf', 52, 202);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZH185ZH', 'Chrysler Town & Country', 53, 124);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HM244HM', 'Buick Regal', 67, 278);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZO279ZO', 'Ford Fiesta', 46, 170);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UK741UK', 'INFINITI Qx50', 82, 144);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JZ124JZ', 'Jaguar F-Type', 41, 251);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CF838CF', 'Jeep Renegade', 71, 374);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CR785CR', 'Acura Ilx', 96, 77);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MU177MU', 'Chevrolet City Express', 56, 437);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GY108GY', 'Volkswagen Jetta', 4, 398);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ND563ND', 'Hyundai Tucson', 19, 345);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JN063JN', 'INFINITI Qx80', 31, 15);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MG993MG', 'Toyota Avalon', 64, 79);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SD011SD', 'Nissan Rogue', 77, 480);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HI583HI', 'MINI Paceman', 40, 238);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LB468LB', 'Volkswagen Golf R', 6, 475);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OP058OP', 'BMW X6', 48, 485);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HM364HM', 'Nissan Rogue Select', 91, 271);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JD038JD', 'BMW I8', 6, 282);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WW698WW', 'GMC Sierra 3500 Hd Crew Cab', 4, 57);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KQ943KQ', 'Ram 3500 Crew Cab', 94, 196);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SB952SB', 'Dodge Viper', 93, 282);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GC702GC', 'Freightliner Sprinter 2500 Passenger', 64, 47);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KZ644KZ', 'Lamborghini Huracan', 18, 169);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TE131TE', 'Audi A8', 28, 119);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KS427KS', 'GMC Acadia', 61, 78);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VO671VO', 'Ram 2500 Crew Cab', 54, 22);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RC242RC', 'Hyundai Elantra Gt', 90, 199);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DO204DO', 'GMC Sierra 3500 Hd Double Cab', 10, 26);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OA116OA', 'Ford F350 Super Duty Crew Cab', 97, 335);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UY243UY', 'Ford Transit 350 Van', 1, 413);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SU676SU', 'Jaguar Xf', 35, 170);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WL491WL', 'Bentley Flying Spur', 74, 270);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SR718SR', 'Ram C/V Tradesman', 6, 447);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VI870VI', 'Jeep Patriot', 30, 38);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HU221HU', 'Lexus Nx', 50, 94);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AZ733AZ', 'Hyundai Genesis Coupe', 50, 483);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EL595EL', 'Volkswagen E-Golf', 32, 423);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RC185RC', 'Ford Explorer', 72, 21);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JM628JM', 'Toyota Rav4', 88, 147);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JE922JE', 'Bentley Mulsanne', 10, 84);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DY050DY', 'Chevrolet Silverado 1500 Crew Cab', 77, 122);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PU361PU', 'Toyota Prius V', 43, 181);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RE777RE', 'Ram 1500 Regular Cab', 15, 102);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XF113XF', 'Chevrolet Cruze', 22, 319);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UT172UT', 'Honda Fit', 86, 128);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZX778ZX', 'Ram 2500 Regular Cab', 22, 337);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JK695JK', 'Toyota Avalon', 21, 424);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZC579ZC', 'Ford Transit 250 Van', 18, 281);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QE878QE', 'Ford Expedition', 20, 414);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PX895PX', 'Dodge Durango', 20, 134);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GG601GG', 'Land Rover Range Rover Sport', 73, 500);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QF983QF', 'Hyundai Elantra Gt', 88, 23);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JX060JX', 'Ferrari 458 Spider', 3, 239);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZQ655ZQ', 'INFINITI Qx70', 37, 28);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GW809GW', 'Volkswagen Golf Sportwagen', 31, 163);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TX028TX', 'INFINITI Q60', 45, 93);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NA513NA', 'Nissan Frontier King Cab', 17, 366);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ET242ET', 'Nissan Frontier King Cab', 37, 440);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PI321PI', 'Nissan Sentra', 39, 201);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HP683HP', 'Chevrolet Traverse', 20, 102);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EF044EF', 'GMC Canyon Crew Cab', 54, 29);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WA143WA', 'Ford Transit Connect Cargo', 54, 319);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YO148YO', 'Ram 2500 Crew Cab', 84, 371);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UF773UF', 'Toyota Tacoma Access Cab', 76, 391);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KH709KH', 'Chevrolet Impala', 19, 345);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('VF580VF', 'Ford Edge', 27, 323);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MH160MH', 'Ford Transit Connect Passenger', 7, 235);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EF063EF', 'Chevrolet Express 2500 Passenger', 11, 402);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GW816GW', 'Nissan Titan Crew Cab', 66, 495);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('UP057UP', 'Dodge Durango', 13, 348);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GL399GL', 'Ram Promaster Cargo Van', 43, 264);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YZ569YZ', 'MINI Convertible', 61, 493);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NI579NI', 'Ferrari 458 Speciale', 49, 390);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RT179RT', 'Toyota Tundra Crewmax', 73, 477);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AP348AP', 'Ford F350 Super Duty Crew Cab', 1, 146);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('TA754TA', 'MAZDA Cx-9', 10, 41);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SR222SR', 'Mercedes-Benz M-Class', 7, 307);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EX075EX', 'Lexus Rx', 28, 293);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HY531HY', 'BMW 4 Series', 79, 18);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BU224BU', 'Chevrolet Corvette', 58, 409);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('HK467HK', 'Toyota Rav4', 35, 313);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KQ855KQ', 'Chevrolet Malibu', 73, 421);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('JE006JE', 'Nissan Nv2500 Hd Cargo', 61, 187);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OA848OA', 'GMC Yukon', 94, 492);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DA128DA', 'Mercedes-Benz Slk-Class', 65, 203);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NU302NU', 'BMW X6', 8, 165);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PQ955PQ', 'Ram Promaster Window Van', 93, 118);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QO074QO', 'Scion Fr-S', 33, 50);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KI033KI', 'Audi A3', 7, 231);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ON453ON', 'Ferrari 458 Speciale', 64, 330);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BW435BW', 'Audi S6', 38, 302);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PN178PN', 'BMW X6', 22, 106);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SW540SW', 'Toyota Sienna', 62, 30);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('RJ601RJ', 'Nissan Altima', 57, 204);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IG981IG', 'Hyundai Santa Fe', 23, 288);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FZ489FZ', 'Lincoln Mkc', 95, 225);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZB615ZB', 'GMC Yukon Xl', 63, 229);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BF761BF', 'Hyundai Elantra Gt', 45, 256);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IY283IY', 'Ford Transit 150 Wagon', 89, 407);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XM871XM', 'GMC Canyon Extended Cab', 85, 179);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('IK583IK', 'Chevrolet Ss', 60, 291);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZJ919ZJ', 'Freightliner Sprinter 2500 Passenger', 73, 361);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('PB737PB', 'INFINITI Qx60', 8, 334);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('LH497LH', 'Toyota Venza', 13, 487);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('OB883OB', 'Mercedes-Benz M-Class', 74, 114);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('FA678FA', 'Mitsubishi Outlander', 78, 371);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NT677NT', 'Honda Fit', 37, 47);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BX893BX', 'Land Rover Range Rover Sport', 90, 229);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WV920WV', 'Ferrari Ff', 36, 403);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QP793QP', 'Chevrolet Volt', 81, 77);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GC637GC', 'Jeep Wrangler', 27, 67);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('DK630DK', 'BMW M5', 33, 35);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QN865QN', 'Mercedes-Benz Sprinter 3500 Cargo', 64, 12);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('YF425YF', 'Jaguar F-Type', 63, 362);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SE458SE', 'Audi S3', 76, 3);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('GF936GF', 'Chevrolet Silverado 1500 Double Cab', 22, 249);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CX020CX', 'Nissan Nv200', 42, 61);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('MV774MV', 'Chevrolet Silverado 1500 Regular Cab', 41, 158);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XM152XM', 'Ford Transit 350 Van', 82, 496);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KW732KW', 'Volvo V60', 16, 238);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WO866WO', 'Mitsubishi Outlander Sport', 24, 460);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('NC506NC', 'Ram Promaster City', 61, 341);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('WP670WP', 'Kia Optima', 88, 214);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XF989XF', 'Honda Cr-Z', 58, 185);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZH959ZH', 'Lincoln Mkz', 61, 189);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('CJ234CJ', 'Honda Fit', 3, 216);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('EX030EX', 'Ford Transit 150 Van', 89, 489);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('XT419XT', 'BMW 7 Series', 77, 445);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('BP937BP', 'GMC Savana 2500 Passenger', 87, 372);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('KR478KR', 'Ford Transit 350 Van', 82, 88);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('ZG578ZG', 'MINI Roadster', 47, 401);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('QS729QS', 'Audi Q3', 76, 54);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('SN528SN', 'Volvo V60', 68, 133);
INSERT INTO AUTOMOBILI (targa, modello, proprietario, dispositivo) VALUES ('AS717AS', 'Porsche Macan', 46, 51);
