INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('GX503GX', 'Jeep Grand Cherokee', 32, 24);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('BS014BS', 'BMW M3', 47, 43);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('WE009WE', 'Volkswagen Golf R', 43, 41);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('FC052FC', 'Toyota Prius', 1, 13);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('WP189WP', 'MAZDA Mazda5', 26, 36);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('EM979EM', 'Freightliner Sprinter 3500 Cargo', 57, 46);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('VM132VM', 'Audi A4', 78, 6);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('WH954WH', 'Ford Transit 150 Van', 2, 11);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('DM320DM', 'Chevrolet Express 3500 Passenger', 97, 22);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('MS633MS', 'Audi Q5', 14, 9);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('TC416TC', 'MAZDA Mx-5 Miata', 86, 30);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('GX601GX', 'GMC Acadia', 52, 23);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('JZ698JZ', 'Lexus Ls', 36, 48);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('MW648MW', 'Ford F350 Super Duty Regular Cab', 65, 22);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('NF306NF', 'Toyota Yaris', 12, 18);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('KC800KC', 'Hyundai Santa Fe Sport', 16, 3);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('ZS651ZS', 'Toyota Land Cruiser', 21, 41);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('VQ607VQ', 'Toyota Tacoma Access Cab', 49, 46);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('EU095EU', 'Ford F450 Super Duty Crew Cab', 55, 32);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('DI340DI', 'Lamborghini Aventador', 68, 17);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('QA768QA', 'Freightliner Sprinter 2500 Passenger', 68, 47);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('YS830YS', 'Toyota Prius C', 73, 44);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('TW556TW', 'Lamborghini Aventador', 43, 15);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('TN439TN', 'BMW Z4', 9, 17);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('UG739UG', 'MINI Roadster', 11, 50);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('QF594QF', 'Toyota Sienna', 65, 24);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('UX991UX', 'Toyota Camry', 82, 14);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('FV989FV', 'Ford F350 Super Duty Super Cab', 73, 8);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('BF534BF', 'Mercedes-Benz G-Class', 59, 18);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('RE341RE', 'Nissan Leaf', 93, 12);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('CW404CW', 'MAZDA Mazda5', 30, 2);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('MK611MK', 'Kia Optima', 53, 40);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('UR040UR', 'Hyundai Veloster', 2, 34);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('YM374YM', 'FIAT 500L', 14, 10);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('GR877GR', 'Chevrolet Express 3500 Cargo', 92, 12);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('IO033IO', 'Ferrari 458 Speciale', 53, 45);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('FW342FW', 'Honda Odyssey', 51, 29);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('QH910QH', 'Cadillac Cts', 9, 5);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('ZR565ZR', 'Ferrari 458 Italia', 63, 37);
INSERT INTO AUTOMOBILI (targa, modello, cliente, dispositivo) VALUES ('PT486PT', 'BMW X1', 11, 42);
