-- Mostra i tragitti più frequentati.

SELECT C1.nome AS INGRESSO, C2.nome AS USCITA, COUNT(*) AS NUM_PERCORRENZE
FROM (TRAGITTI T JOIN CASELLI C1 ON T.ingresso = C1.nome) JOIN CASELLI C2
ON T.uscita = C2.nome
GROUP BY C1.nome, C2.nome
ORDER BY NUM_PERCORRENZE DESC;
