-- Mostra i tragitti più frequentati.

SELECT INGRESSI.nome AS INGRESSO, USCITE.nome AS USCITA, COUNT(*) AS NUM_PERCORRENZE
FROM (TRAGITTI T JOIN CASELLI INGRESSI ON T.ingresso = INGRESSI.id) JOIN CASELLI USCITE
ON T.uscita = USCITE.id
GROUP BY (INGRESSO, USCITA)
ORDER BY NUM_PERCORRENZE DESC;
